destination: production
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    smart_quotes: ["apos", "apos", "quot", "quot"]
paginate: 10
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-redirect-from
